service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  region: ap-south-1
functions:
  graphql:
    handler: ./src/server.graphqlHandler
    events:
      - httpApi:
          path: /graphql
          method: POST
    environment:
      MONGO_URI: ${env:MONGO_URI}
plugins:
  - serverless-plugin-typescript